In [73]:
import pandas as pd
df = pd.read_csv("../data/survey.csv")

df.head()

,Timestamp,Have you moved out of university accommodation or a rental property before?,"When moving out, have you ever had unwanted household items that were still usable?",What type of accommodation were you living in when you most recently moved out?,How many times have you moved out of university accommodation or rental housing?,"Thinking about your most recent move-out, what did you do with unwanted but still usable household items? Select all that apply.",Which option did you try first?,"If you have ever thrown away an unwanted but still usable household item, which factors contributed to your decision to discard it rather than reuse or redistribute it? Select all that apply.",What type of unwanted but still usable items have you had when moving out? Select all that apply.,Which THREE factors have the greatest influence on what you do with an unwanted but usable item when moving out? (Select up to 3.),...,"Before your most recent move-out, which of the following had you come across as ways to pass on unwanted but still usable household items? Select one option per row. [Charity shops / donation centres]","Before your most recent move-out, which of the following had you come across as ways to pass on unwanted but still usable household items? Select one option per row. [Other]",Have you ever tried to sell or give away unwanted items?,Which THREE parts of selling or giving away unwanted items did you find most difficult? (Select up to 3.),"During your most recent move-out, if you had multiple unwanted but usable items, what made managing them difficult, if anything? Select all that apply.","For a low-value but usable item, how much active time in total would you be willing to spend listing it, messaging others, and arranging pickup?",How concerned would you be about meeting someone you do not know to give away or collect an item?,"What, if anything, would make you uncomfortable about giving an item to someone you do not know? Select all that apply.",Which THREE outcomes would be most helpful when trying to redistribute unwanted items during move-out? (Select up to 3.),Is there anything else that would have made dealing with unwanted usable items easier during your most recent move-out?
0,03/09/2026 08:54:17,Yes,Yes,University accommodation,Once,"Give them away to friends/housemates, Donate t...",Give them away to friends/housemates,"I need to get rid of it quickly, It takes too ...","Kitchenware & cookware (e.g. plates, bowls, po...","How quickly I need to get rid of it, Amount of...",...,"Considered using it, but didn't",Never heard of it,Yes,"Setting a price, Finding interested people, Pe...","Taking photos of multiple items, Messaging dif...",10–30 minutes,3.0,"Sharing my home address, Sharing my phone numb...",Be more confident that someone will collect th...,NaN
1,03/09/2026 10:07:30,Yes,Yes,University accommodation,Twice,"Sell them, Give them away to friends/housemate...",Throw them away,"I need to get rid of it quickly, It takes too ...","Furniture (e.g. chairs, tables, shelves, desks...","How quickly I need to get rid of it, Amount of...",...,"Heard of it, but never considered using it",Never heard of it,Yes,"Describing the item, Setting a price, Negotiating","Creating separate listings, Writing descriptio...",10–30 minutes,3.0,"Sharing my home address, Sharing my phone numb...","Spend less time messaging and coordinating, Re...",No
2,03/09/2026 10:16:49,Yes,Yes,University accommodation,Once,"Give them away to friends/housemates, Leave th...",Give them away to friends/housemates,"It takes too much effort to arrange, I am not ...","Furniture (e.g. chairs, tables, shelves, desks...","Likelihood of finding someone who wants it, Co...",...,"Heard of it, but never considered using it","Heard of it, but never considered using it",Yes,"Describing the item, Finding interested people...","Taking photos of multiple items, Writing descr...",10–30 minutes,2.0,Meeting in a private or unfamiliar location,Find suitable people who want the item more ea...,没有
3,03/09/2026 10:21:04,Yes,Yes,Shared rental,3+ times,"Sell them, Throw them away",Sell them,"I need to get rid of it quickly, It takes too ...","Bedding & textiles (e.g. pillows, blankets, sh...","How quickly I need to get rid of it, Likelihoo...",...,"Heard of it, but never considered using it",Never heard of it,Yes,"Finding interested people, Responding to messa...","Messaging different people, Keeping track of w...",Less than 10 minutes,2.0,"Sharing my home address, Sharing my phone numb...",Be more confident that someone will collect th...,NaN
4,03/09/2026 10:22:00,Yes,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
df.columns = [
    'timestamp',
    'has_moved_out',
    'had_usable_unwanted_items',
    'accommodation_type',
    'move_out_count',
    'item_disposition',
    'first_option',
    'discard_factors',
    'item_types',
    'decision_factors',
    'action_three_weeks',
    'action_one_two_days',
    'deadline_concern',
    'awareness_online_marketplaces',
    'awareness_university_groups',
    'awareness_social_media',
    'awareness_friends_students',
    'awareness_charity',
    'awareness_other',
    'tried_redistribution',
    'redistribution_difficulties',
    'multiple_item_difficulties',
    'willing_time',
    'stranger_concern',
    'stranger_discomfort',
    'desired_outcomes',
    'other_feedback'
]

df.columns

Index(['timestamp', 'has_moved_out', 'had_usable_unwanted_items',
       'accommodation_type', 'move_out_count', 'item_disposition',
       'first_option', 'discard_factors', 'item_types', 'decision_factors',
       'action_three_weeks', 'action_one_two_days', 'deadline_concern',
       'awareness_online_marketplaces', 'awareness_university_groups',
       'awareness_social_media', 'awareness_friends_students',
       'awareness_charity', 'awareness_other', 'tried_redistribution',
       'redistribution_difficulties', 'multiple_item_difficulties',
       'willing_time', 'stranger_concern', 'stranger_discomfort',
       'desired_outcomes', 'other_feedback'],
      dtype='str')

In [75]:
df.isna().sum()

timestamp                         0
has_moved_out                     0
had_usable_unwanted_items         0
accommodation_type                4
move_out_count                    4
item_disposition                  4
first_option                      4
discard_factors                   4
item_types                        4
decision_factors                  4
action_three_weeks                4
action_one_two_days               4
deadline_concern                  4
awareness_online_marketplaces     4
awareness_university_groups       4
awareness_social_media            4
awareness_friends_students        4
awareness_charity                 4
awareness_other                   4
tried_redistribution              4
redistribution_difficulties       4
multiple_item_difficulties        4
willing_time                      4
stranger_concern                  4
stranger_discomfort               4
desired_outcomes                  4
other_feedback                   34
dtype: int64

In [76]:
analysis_df = df[
    (df["has_moved_out"] == "Yes") &
    (df["had_usable_unwanted_items"] == "Yes")
].copy()

print("Number of respondents:", len(analysis_df))

Number of respondents: 39

In [77]:
analysis_df.head()
analysis_df.shape

(39, 27)

In [78]:
def count_multiple_choice(df, column):
    return (
        df[column]
        .dropna()
        .str.split(", ")
        .explode()
        .value_counts()
    )

In [79]:
print(analysis_df.columns)

Index(['timestamp', 'has_moved_out', 'had_usable_unwanted_items',
       'accommodation_type', 'move_out_count', 'item_disposition',
       'first_option', 'discard_factors', 'item_types', 'decision_factors',
       'action_three_weeks', 'action_one_two_days', 'deadline_concern',
       'awareness_online_marketplaces', 'awareness_university_groups',
       'awareness_social_media', 'awareness_friends_students',
       'awareness_charity', 'awareness_other', 'tried_redistribution',
       'redistribution_difficulties', 'multiple_item_difficulties',
       'willing_time', 'stranger_concern', 'stranger_discomfort',
       'desired_outcomes', 'other_feedback'],
      dtype='str')

In [80]:
analysis_df = analysis_df.drop(columns="other_feedback")

In [81]:
print(analysis_df.shape)

(39, 26)

In [82]:
analysis_df.to_csv("../data/cleaned_survey.csv", index=False)

In [83]:
print("Original:", len(df))

print("\nMoved out:")
print(df["has_moved_out"].value_counts(dropna=False))

print("\nHad usable unwanted items:")
print(df["had_usable_unwanted_items"].value_counts(dropna=False))

Original: 44

Moved out:
has_moved_out
Yes    40
No      4
Name: count, dtype: int64

Had usable unwanted items:
had_usable_unwanted_items
Yes    40
No      4
Name: count, dtype: int64

In [84]:
from IPython.display  import display
excluded_df = df[
    ~(
        (df["has_moved_out"] == "Yes") &
        (df["had_usable_unwanted_items"] == "Yes")
    )
].copy()

print("Excluded:", len(excluded_df))

display(
    excluded_df[
        ["has_moved_out", "had_usable_unwanted_items"]
    ]
)

Excluded: 5

   has_moved_out had_usable_unwanted_items
4            Yes                        No
18            No                       Yes
28            No                        No
40            No                        No
41            No                        No

In [85]:
# Assuming your cleaned dataframe is named 'df' and is already filtered to N=39
# Calculate Accommodation Type (Q3)
accom_counts = df['accommodation_type'].value_counts()
accom_percent = (accom_counts / len(df)) * 100
print("Accommodation Type Percentages:\n", accom_percent)

# Calculate Times Moved Out (Q4)
moved_counts = df['move_out_count'].value_counts()
moved_percent = (moved_counts / len(df)) * 100
print("\nTimes Moved Out Percentages:\n", moved_percent)

Accommodation Type Percentages:
 accommodation_type
Shared rental               43.181818
Private rental              25.000000
University accommodation    22.727273
Name: count, dtype: float64

Times Moved Out Percentages:
 move_out_count
Twice       40.909091
Once        36.363636
3+ times    13.636364
Name: count, dtype: float64